# 
GET http://localhost:3000/


### 模拟不存在数据的用户登录🚪 ----------------在 4000 端口服务器上
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Rayn"
}
### 模拟不存在数据的用户退出登录🚪 ----------------在 4000 端口服务器上
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmF5biIsImlhdCI6MTcxNTY0MTc2Mn0.XglZhP6Iu7M1c3DBamt5YrWlpNuAW2bVX-7EIUu7Vy8"
}
### 模拟Nicky-access失效重新获取token⌛️ ----------------在 4000 端口服务器上
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmF5biIsImlhdCI6MTcxNTY0MTc2Mn0.XglZhP6Iu7M1c3DBamt5YrWlpNuAW2bVX-7EIUu7Vy8"
}

### 模拟Nicky获取数据库数据📊----------------在 3000 端口服务器上
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmF5biIsImlhdCI6MTcxNTY0MTc3NSwiZXhwIjoxNzE1NjQxNzkwfQ.dUnI-Wew-s1jb0Q4oIxx0RnYlM1XZTSRP9c87TIK-P4
